name: Query devstats

on:
  push:
    branches:
      - main
      - v*

jobs:
  build-devstats:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanv/devstats-download-action@main
        with:
          repo: scientific-python/spin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: devstats-spin
