name: Build book

on:
  push:
    branches:
      - main
      - v*

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Set edition prefix
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
              echo "EDITION_PREFIX=" >> $GITHUB_ENV
          else
              echo "EDITION_PREFIX=${{ github.ref_name }}/" >> $GITHUB_ENV
          fi

      - name: Test variable
        run: |
          echo "https://my-site.org/${EDITION_PREFIX}book"
