name: Query devstats

on:
  push:
    branches:
      - main
      - v*

jobs:
  devstats-query:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanv/devstats-download-action@main
        with:
          repos: "[scientific-python/spin]"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: devstats-spin
