name: Labels

on:
  pull_request:
    types:
      - opened
      - repoened
      - labeled
      - unlabeled
      - synchronize

env:
  LABELS: ${{ toJson(github.event.pull_request.labels }}

jobs:
  check-type-label:
    name: ensure type label
    runs-on: ubuntu-latest
    steps:
      - name: Ensure single label
        run: |
          N=$(echo $LABELS | jq 'map( select (.name | startswith("type:"))) | length')
          if [[ $N != 1 ]]; then
            exit 1
          fi
